# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on:
  pull_request:
    branches: ["000000000000"]
    # branches: ["main"]

name: Test

jobs:
  test:
    concurrency:
      group: ${{ github.workflow }}-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # specify your Node.js version here
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: make test
